//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DvdSubExtractor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DvdFolderPath {
            get {
                return ((string)(this["DvdFolderPath"]));
            }
            set {
                this["DvdFolderPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OutputDirectory {
            get {
                return ((string)(this["OutputDirectory"]));
            }
            set {
                this["OutputDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public float MinimumDvdTrackLength {
            get {
                return ((float)(this["MinimumDvdTrackLength"]));
            }
            set {
                this["MinimumDvdTrackLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int SampleVideoLength {
            get {
                return ((int)(this["SampleVideoLength"]));
            }
            set {
                this["SampleVideoLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\VideoLAN\\VLC\\vlc.exe")]
        public string SampleVideoPlayerPath {
            get {
                return ((string)(this["SampleVideoPlayerPath"]));
            }
            set {
                this["SampleVideoPlayerPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tahoma")]
        public string SubitleFileFontName {
            get {
                return ((string)(this["SubitleFileFontName"]));
            }
            set {
                this["SubitleFileFontName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SubtitleStyle {
            get {
                return ((int)(this["SubtitleStyle"]));
            }
            set {
                this["SubtitleStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\Aegisub\\aegisub32.exe")]
        public string SubtitleEditorPath {
            get {
                return ((string)(this["SubtitleEditorPath"]));
            }
            set {
                this["SubtitleEditorPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\MeGUI\\tools\\dgindex\\DGIndex.exe")]
        public string DgIndexPath {
            get {
                return ((string)(this["DgIndexPath"]));
            }
            set {
                this["DgIndexPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int FontSizeAdjustmentPercent {
            get {
                return ((int)(this["FontSizeAdjustmentPercent"]));
            }
            set {
                this["FontSizeAdjustmentPercent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SubtitleFontBold {
            get {
                return ((bool)(this["SubtitleFontBold"]));
            }
            set {
                this["SubtitleFontBold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.4")]
        public float SubtitleFontOutline {
            get {
                return ((float)(this["SubtitleFontOutline"]));
            }
            set {
                this["SubtitleFontOutline"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.7")]
        public float SubtitleFontShadow {
            get {
                return ((float)(this["SubtitleFontShadow"]));
            }
            set {
                this["SubtitleFontShadow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int SubtitleVerticalMargin {
            get {
                return ((int)(this["SubtitleVerticalMargin"]));
            }
            set {
                this["SubtitleVerticalMargin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int SubtitleHorizontal4x3Margin {
            get {
                return ((int)(this["SubtitleHorizontal4x3Margin"]));
            }
            set {
                this["SubtitleHorizontal4x3Margin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int SubtitleHorizontal16x9Margin {
            get {
                return ((int)(this["SubtitleHorizontal16x9Margin"]));
            }
            set {
                this["SubtitleHorizontal16x9Margin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("228, 223, 226")]
        public global::System.Drawing.Color SubtitleForeColor {
            get {
                return ((global::System.Drawing.Color)(this["SubtitleForeColor"]));
            }
            set {
                this["SubtitleForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SubtitleColorScheme {
            get {
                return ((int)(this["SubtitleColorScheme"]));
            }
            set {
                this["SubtitleColorScheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("224, 0, 0, 0")]
        public global::System.Drawing.Color SubtitleBorderColor {
            get {
                return ((global::System.Drawing.Color)(this["SubtitleBorderColor"]));
            }
            set {
                this["SubtitleBorderColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("56, 0, 0, 0")]
        public global::System.Drawing.Color SubtitleShadingColor {
            get {
                return ((global::System.Drawing.Color)(this["SubtitleShadingColor"]));
            }
            set {
                this["SubtitleShadingColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string KerningAdjustMRU {
            get {
                return ((string)(this["KerningAdjustMRU"]));
            }
            set {
                this["KerningAdjustMRU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("32")]
        public float SubtitleFontDefaultSize {
            get {
                return ((float)(this["SubtitleFontDefaultSize"]));
            }
            set {
                this["SubtitleFontDefaultSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool StoreSupTextInSourceDir {
            get {
                return ((bool)(this["StoreSupTextInSourceDir"]));
            }
            set {
                this["StoreSupTextInSourceDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RemoveSDHSet {
            get {
                return ((bool)(this["RemoveSDHSet"]));
            }
            set {
                this["RemoveSDHSet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ScaleSubtitleBitmap {
            get {
                return ((bool)(this["ScaleSubtitleBitmap"]));
            }
            set {
                this["ScaleSubtitleBitmap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool StoreSrtAsANSI {
            get {
                return ((bool)(this["StoreSrtAsANSI"]));
            }
            set {
                this["StoreSrtAsANSI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DataFileInExeDirectory {
            get {
                return ((bool)(this["DataFileInExeDirectory"]));
            }
            set {
                this["DataFileInExeDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string InitialBrowseDirectory {
            get {
                return ((string)(this["InitialBrowseDirectory"]));
            }
            set {
                this["InitialBrowseDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InitialStepIsBrowse {
            get {
                return ((bool)(this["InitialStepIsBrowse"]));
            }
            set {
                this["InitialStepIsBrowse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PositionSubs {
            get {
                return ((int)(this["PositionSubs"]));
            }
            set {
                this["PositionSubs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SpanishSpecialCharacters {
            get {
                return ((bool)(this["SpanishSpecialCharacters"]));
            }
            set {
                this["SpanishSpecialCharacters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WaitForEnterDuringOcr {
            get {
                return ((bool)(this["WaitForEnterDuringOcr"]));
            }
            set {
                this["WaitForEnterDuringOcr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FrenchSpecialCharacters {
            get {
                return ((bool)(this["FrenchSpecialCharacters"]));
            }
            set {
                this["FrenchSpecialCharacters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LargeMode {
            get {
                return ((bool)(this["LargeMode"]));
            }
            set {
                this["LargeMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SavedKerningValues {
            get {
                return ((string)(this["SavedKerningValues"]));
            }
            set {
                this["SavedKerningValues"] = value;
            }
        }
    }
}
